Change the `_compute_flux_spatial` method on `MapEvaluator`
gammapy/gammapy pull request #3145
Opened 2020-12-01 08:50 UTC by fabiopintore

This PR includes some changes in the `_compute_flux_spatial` function in `~gammapy.datasets.map.MapEvaluator`. 
We now allows the function to calculate the integral flux over either a `WcsGeom` or a `RegionNDMap`. The integrated flux is also corrected for the PSF.

To do:
1) We need to add tests!
2) possibility to enlarge the tangential geometry so that the PSF is fully contained.

@LauraOlivera

2020-12-03 12:21 UTC, adonath requested changes
Thanks @fabiopintore, I have left a few comments. Please add a unit test now to check the implementation...

2020-12-03 12:21 UTC, adonath commented on gammapy/datasets/map.py
> +        else:
Just remove the `not isinstance(self.geom, RegionGeom)` before...

2020-12-03 12:21 UTC, adonath commented on gammapy/datasets/map.py
> +            tmp_map = Map.from_geom(geom=wcs_geom, data=values.data,
`.interate_geom()` already returns a `Map` object...no need to create it here...

2020-12-03 12:21 UTC, adonath commented on gammapy/datasets/map.py
> +            value = ((values.data * wcs_geom.solid_angle())).sum()
This misses the application of the region mask, that you had in your previous implementation. As you have called `.integrate_geom()` already, there is no need to multiply again with the solid angle...

2020-12-03 19:15 UTC, adonath requested changes
Thanks @fabiopintore, I would suggest to add a second test using a circular region of the size  of 1 sigma of the Gaussian PSF and check the spread corresponds to ~39%.

2020-12-03 19:15 UTC, adonath commented on gammapy/datasets/tests/test_map.py
> +    exposure_wcs = Map.create(axes=[energy_axis_true], region=region, map_type="region")
Note this does not create a `WCSMap`, but again a `RegionMap`, for a WCS map you need to choose `map_type="wcs"`...please adapt the test.

2020-12-06 11:41 UTC, fabiopintore commented
I added a further test to check if a circular region of the 1sigma value of the PSF contains the correct amount of flux. 
@adonath, @LauraOlivera  please may you check if I made the right things? The tests pass, but it seems to me that the predicted counts, when using a `RegionGeom`, are too much than expected for the given exposure...

2020-12-07 10:55 UTC, adonath requested changes
Thanks @fabiopintore, I noticed a bug in the implementation and made a proposal for a better unit test...

2020-12-07 10:55 UTC, adonath commented on gammapy/datasets/map.py
> +            value = (values.data[mask]).sum()
I started to test implementation and I noticed a bug in this line: we have to sum only over the spatial axes here and not all axes (and not including the energy axis). So the statement here should be something like `.sum(axis=(1, 2))`... I need to check whether the implementation in `SpatialModel.integrate_geom()` is correct.

2020-12-07 10:55 UTC, adonath commented on gammapy/datasets/tests/test_map.py
> +def test_compute_flux_spatial():
I realised this test case is maybe a bit to high level. What about if we start on the `MapEvaluator` level?
So define:
- Constant exposure (filled with ones...) with 2 energy bins
- Point source models with a `ConstSpectralModel`
- Gaussian PSF kernel, created with `PSFKernel.from_gauss(geom=region_geom.to_wc_geom())`
- Create a `MapEvaluator()`
- `MapEvaluator.compute_flux_spatial()` should then return exactly the PSF containment per energy as an array like [0.39, 0.39]...

2020-12-09 09:11 UTC, adonath approved these changes
Thanks @fabiopintore!

2020-12-09 09:11 UTC, merged