Add optimizer option to estimators
gammapy/gammapy pull request #3317
Opened 2021-04-16 14:28 UTC by QRemy

This PR add backend, optimize_opts, and covariance_opts options from`Fit.run()` to the `estimators.run()` methods`and their associated evaluate methods. 

Also set FluxEstimator._parameter_estimator as a property

2021-04-16 15:38 UTC, registerrier commented
Thanks @QRemy . Having the possibility to modify the minimizer is indeed very useful. 
Maybe the arguments can be passed in the form of a dictionary, since they might evolve in the future?

2021-04-29 07:23 UTC, adonath requested changes
Thanks @QRemy, so far I don't have any comments. However please rebase and fix the remaining merge conflict...

2021-04-29 07:23 UTC, adonath commented on gammapy/analysis/core.py
> +    def get_excess_map(self):
No sure why the is included here, must be a merge conflict...

2021-05-03 14:07 UTC, adonath approved these changes
Thanks @QRemy for the rebase! I'll merge this PR and then we can continue later this week...

2021-05-03 14:07 UTC, merged