Use string for model name in spread_signal()
gammapy/gammapy pull request #3397
Opened 2021-06-23 15:05 UTC by AtreyeeS

This PR fixes #3386

2021-06-23 15:39 UTC, AtreyeeS commented
I imagine that the doc test fail is unrelated.

2021-06-23 16:07 UTC, adonath commented
Thanks @AtreyeeS, please remove the unrelated `test_stack.ipynb` notebook.

2021-06-23 19:14 UTC, adonath requested changes
Thanks @AtreyeeS, I have left two minor inline comments...

2021-06-23 19:14 UTC, adonath commented on gammapy/datasets/map.py
> +            except:
It's important to always specify the kind of error to catch like `except KeyError`. Also the new error message you give is not really an improvement (it missed which key is not contained). My proposal would be to just keep the `KeyError`, that is raised if the `model_name` does  not exist.

2021-06-23 19:14 UTC, adonath commented on gammapy/datasets/map.py
> +        model: str
Maybe rename to `model_name` to make the change more explicit.

2021-06-24 07:42 UTC, adonath commented
Thanks @AtreyeeS, once the remaining test fails are solved this is real to merge...

2021-06-24 08:36 UTC, adonath approved these changes
Thanks @AtreyeeS! Remaining test fails are unrelated...

2021-06-24 08:36 UTC, merged