Change definition of disk edge parameter
gammapy/gammapy pull request #3412
Opened 2021-07-06 12:26 UTC by adonath

**Description**

This pull request changes the definition of the `edge` parameter to a relative fraction of `r_0`. This solves the problem mentioned in https://github.com/gammapy/gammapy/pull/3229#issuecomment-874640578. To make the change more explicit I decided to rename the parameter to `edge_width` as well.

2021-07-07 15:26 UTC, luca-giunti requested changes

2021-07-07 15:26 UTC, luca-giunti commented on gammapy/modeling/models/spatial.py
> +        smooth edge of the model drops from 95% to 5% of its amplitude.
Thanks @adonath! The only comment I have is that this sentence should probably be re-formulated

2021-07-07 15:28 UTC, luca-giunti commented on gammapy/modeling/models/spatial.py
> +        smooth edge of the model drops from 95% to 5% of its amplitude.
Or maybe just "within which"

2021-07-08 09:02 UTC, luca-giunti approved these changes

2021-07-08 09:29 UTC, adonath commented
Thanks @luca-giunti!

2021-07-08 09:29 UTC, merged