Mamba doc update
gammapy/gammapy pull request #3730
Opened 2022-01-25 10:22 UTC by facero

**Description**

This PR is to adress the issue #3710. It adds a short description of mamba in the `getting started` and  `dev` docs as an alternative to conda.
While mamba can also be used as a full replacement for conda (e.g. `mamba activate gammapy-0.19`), I prefer to stick to use mamba just for installation to reduce confusion in users mind ;-)

I also updated the dev doc (intro.rst) to mention using `conda activate` by default instead of `source activate`.
The switch in conda happened in 2017. I imagine most of users have conda > 4.4 today.

2022-01-25 21:52 UTC, registerrier reviewed
Thanks @facero ! 
This will need a rebase now that PR #3722 has been merged.

2022-01-26 11:38 UTC, maxnoe commented on docs/development/intro.rst
> +    #To speed up the environment solving you can use mamba as an alternative
Maybe link to the mamba docs here?

2022-01-26 12:20 UTC, Bultako requested changes
@facero 

The file `getting-started/quickstart.rst` has been renamed into `getting-started/index.rst` in the [new version of the docs](https://docs.gammapy.org/dev/getting-started/index.html).
So you can safely remove the `getting-started/quickstart.rst` file and modify the `getting-started/index.rst` file instead.

2022-01-26 13:55 UTC, facero commented on docs/development/intro.rst
> +    #To speed up the environment solving you can use mamba as an alternative
Done

2022-01-26 14:30 UTC, Bultako commented
@facero 
please, remove the `getting-started/quickstart.rst` file from the PR, this file is not needed because it has been renamed :)

2022-01-26 17:42 UTC, Bultako approved these changes

2022-01-26 17:43 UTC, Bultako commented
Thanks @facero !

2022-01-26 17:43 UTC, merged