Counts stat sum
gammapy/gammapy pull request #3798
Opened 2022-02-13 21:07 UTC by registerrier

**Description**

This pull request adds a `sum` attribute to `CountStatistics` classes. It also adds an addition operator. This leaves the handling of e.g. `alpha` averaging to the class itself when the user wants to combine different measurements.
It also adds a `__getitem__` method to allow access to subarrays via masking.

This implementation could simplify a bit some statistics calculations in `MapDataset`.

**Dear reviewer**

2022-03-19 21:03 UTC, adonath requested changes
Thanks a lot @registerrier, I have left a few inline comments to address, mostly on the add operator and indexing behavior.

In general I think we could actually introduce possible `CountsStatistic.info_dict()` as well, which returns the summary as a dict already. This could be useful for quick looks...

I was also wondering to maybe introduce a public API for `Dataset` -> `CountStatistics`. I don't have a strong opinion on this, but somehow I see `CountsStatistics` a bit similar in functionality of `Estimator` (just in terms of the quantities it computes), so maybe having something like `CountsStatistic.from_dataset()` would be a bit clearer, however `MapDataset.counts_statistic` could work as well, however it will e.g. not exist for `FluxPointsDataset` and it's definition might go away completely if we introduce a more flexible way fo defining fit statistics. In which case the tight coupling between `MapDataset` and `CountsStastistic` will go away.

2022-04-19 16:45 UTC, adonath commented
@registerrier Do you have time to address the remaining comments?

2022-04-21 20:32 UTC, registerrier commented on gammapy/stats/counts_statistic.py
> +        elif key in [0, slice(None), slice(0,1)]:
Done.

2022-04-21 20:32 UTC, registerrier commented on gammapy/stats/counts_statistic.py
> +    def sum(self):
Done

2022-04-21 20:34 UTC, registerrier commented on gammapy/stats/counts_statistic.py
> +    def __add__(self, other):
I finally removed this. The in-place `stack` method is problematic if this to be used internally with `Dataset` maps. One would avoid modification of the parent maps simply handling the `CountsStatistic`.

2022-04-22 09:05 UTC, adonath requested changes
Thanks @registerrier  I have left one last minor inline comment.

2022-04-22 09:05 UTC, adonath commented on gammapy/stats/counts_statistic.py
> +    def stack(self, other):
Remove...

2022-04-25 14:40 UTC, adonath approved these changes
Thanks @registerrier, I added one minor commit with some cleanup. Otherwise I have no further comments...

2022-04-25 14:41 UTC, merged