Example of a spectrally varying temporal model
gammapy/gammapy pull request #3838
Opened 2022-03-04 17:21 UTC by AtreyeeS

This is a test implementation of a model with time dependent spectral variability. Sorry now, I simply add it as a an example in our models tutorial, as a custom model.

If we decide this is the way to do it, I need to update `TemporalModel.plot()` to accept an energy axis. And of course, polish the tutorial. But before putting in more time, it would be nice to have your opinion if we want to show this @registerrier @adonath @QRemy

2022-03-11 17:00 UTC, adonath reviewed
Thanks a lot @AtreyeeS, the is very useful functionality. My main comment would be to establish the correct behavior here with unit tests.

2022-03-14 17:09 UTC, registerrier commented
A general comment here. 
What is the best approach here?
1. Add an energy evaluation on `TemporalModel` and a `is_energy_dependent` flag as done here?
2. Add a time evaluation on `SpectralModel` and a `is_time_dependent`flag?
I think option 1 adds complexity in the sense that you will still need a `SpectralModel` on top. 
Option 2 does not require an additional model. Also it could in the long run simplify significantly the handling of models by allowing products of `SpectralModel` and `TemporalModel`.

2022-03-16 11:37 UTC, AtreyeeS commented
Thinking about this, I tend to agree with @registerrier 
I started with (1) to be analogous with `SpatialModels` - you **always** need to multiply by a `SpectralModel` for the normalisation parameter (a `ConstantSpectralModel` at least). So the API could be consistent.

But probably it is more intuitive to think of Spectral models with some added temporal variability. I propose that I close this PR and start a new one? @adonath ?

2022-03-18 14:28 UTC, adonath commented
@registerrier As a long term solution I probably also agree, however given the convention we have now, adding the energy dependence to the temporal model seems a bit clearer to me:

```
model(E, t, l, b) = f(E) * g(l, b, E) * h(t, E)
```
Which defines the energy as the main required coordinate. Instead of:
```
model(E, t, l, b) = f(E, t) * g(l, b, E) * h(t)
```
Which basically removes the need for a spectral model. But it's not a strong argument in any case.

2022-05-03 12:55 UTC, adonath commented
What is the status here @AtreyeeS? Would you still like to add those for v1.0rc?

2022-05-09 17:05 UTC, registerrier requested changes
Thanks @AtreyeeS it seems test_energy_dependent_model lacks a `requires_data()` decorator

2022-05-09 17:10 UTC, registerrier commented on gammapy/modeling/models/temporal.py
> +    def integral(self, t_min, t_max, energy=None):
Where is the energy integration performed?

2022-09-09 10:35 UTC, AtreyeeS commented
Closing this PR and opening a new one

2022-09-09 10:35 UTC, closed without merging