Modify SafeMaskMaker to ignore data only below the background peak
gammapy/gammapy pull request #3873
Opened 2022-04-05 17:08 UTC by AtreyeeS

This PR addresses #3851
The energy bin containing the peak of the background is now kept.
Surprisingly, this did not affect any of the fitting test results...

2022-04-08 09:57 UTC, registerrier reviewed
Thanks @AtreyeeS . It is indeed strange that the tests do not change more.

Can it be due to the way the function is designed? Taking the npred on the `Dataset` energy axis is likely insufficient to locate the maximum. 
Currently most safe mask functions rely on the projected IRFs. I think this can be problematic.  Note that the `aeff-default` accesses the `obs.aeff.meta`. 
Another approach could be to find the position of the maximum directly in the `obs.bkg` and exclude all bins with upper edges below the energy.

2022-04-18 10:20 UTC, adonath commented
@AtreyeeS @registerrier I think we do not use the background method in tests do we? What I can see in the diff is that at least the tests, that are expected to change do change.

2022-04-18 10:21 UTC, adonath requested changes
Thanks @AtreyeeS! Please adapt the documentation of the method in the `SafeMaskMaker`, otherwise looks good to me...

2022-04-18 10:21 UTC, adonath commented on gammapy/makers/tests/test_safe.py
> +    assert_allclose(np.all(mask_bkg_peak), True)
Just use `assert np.all(mask_bkg_peak)` here...

2022-04-19 08:34 UTC, AtreyeeS commented
Thanks @adonath ! Should be safe to merge now I think

2022-04-19 16:06 UTC, adonath approved these changes
Thanks @AtreyeeS, no further comments from my side.

2022-04-19 16:06 UTC, merged