Fix error bars on plot_excess method of SpectrumDataset and SpectrumDatasetOnOff and plot_residuals_spectral
gammapy/gammapy pull request #3975
Opened 2022-06-06 04:50 UTC by mdebony

**Description**

This pull request is a for solving issue  #3971 about the incorrect size of the error bars on plot created by the method plot_excess of SpectrumDataset and SpectrumDatasetOnOff. This also add correct error bar computation for all the method of the plot_residuals_spectral method used by all Datasets.

**Dear reviewer**
This is pull request is ready for review.

2022-06-08 15:14 UTC, registerrier requested changes
Thanks @mdebony .

Since this is a bug fix release correction, we should not change the API so the addition of the 'diff/model' option should be left out. 
It would be good to check the impact of the modified 'diff/sqrt(model)' option. How does it impact the resulting plots?

2022-06-09 14:03 UTC, mdebony commented on gammapy/datasets/map.py
> +            yerr = excess_error/npred_spec.data
Ok, as the method is available on the method _compute_residuals which is being used for the plot function, I thought it was worth adding it.

2022-06-09 16:40 UTC, mdebony commented on gammapy/datasets/map.py
> +            yerr = excess_error/np.sqrt(npred_spec.data)
The ones likes was just defaulting the errors bars to one so they weren't really corresponding to anything.
I've added a plot with the two error bars over imposed to show the difference (test base on the tutorial notebook for spectral analysis).
![image](https://user-images.githubusercontent.com/49060820/172899532-b3b4a271-628a-479a-a47d-ffb63c081290.png)

2022-06-10 12:16 UTC, adonath commented
Thanks @mdebony! We should leave a description in the docstring what it actually plots now...to avoid confusion in future.

2022-06-10 12:16 UTC, adonath commented
Thanks @mdebony! We should leave a description in the docstring what it actually plots now...to avoid confusion in future.

2022-06-10 13:46 UTC, mdebony commented
Ok I've added a precision on docstrings of both methods about the way of the error bars are computed. Was it what you were expected ?

2022-06-15 16:00 UTC, registerrier commented on gammapy/datasets/map.py
> +            yerr = excess_error/np.sqrt(npred_spec.data)
OK.I assume that the smaller error bars at high energy are due to the fact that the excess error can become null.

2022-06-15 16:05 UTC, registerrier approved these changes
Thanks @mdebony !

2022-06-15 16:20 UTC, merged