Fix zeros errors in models created from 3HWC catalog
gammapy/gammapy pull request #4013
Opened 2022-06-30 08:51 UTC by QRemy

Fix zeros errors in models created from 3HWC catalog

Requires also: 
https://github.com/gammapy/gammapy-data/pull/26

2022-06-30 08:57 UTC, QRemy commented
Why GitHub action modified the codemeta automatically in this PR and not the previous ones ?

2022-07-06 14:37 UTC, registerrier submitted a review, later dismissed
Thanks @QRemy.

All errors were incorrect with the previous version?
Why is the new ecsv file needed?

2022-07-06 15:21 UTC, QRemy commented on gammapy/catalog/hawc.py
> +            * (np.abs(self.data["spec0_index_errp"]) + np.abs(self.data["spec0_index_errn"])),
yes where errp=errn

2022-07-15 18:49 UTC, registerrier commented
Hi @QRemy the new precision in the HAWC ecsv file is causing some tests to fail. Probably the tolerance should be adapted.

2022-07-19 12:40 UTC, registerrier commented
Hi @QRemy , any chance to correct the test fails caused by the new 3HWC ecsv file?

2022-07-20 15:05 UTC, adonath requested changes
Thanks @QRemy, I have left some inline comments to address...

2022-07-20 15:05 UTC, adonath commented on gammapy/catalog/hawc.py
> +            * (np.abs(self.data["spec0_dnde_errp"]) + np.abs(self.data["spec0_dnde_errp"])),
Why does this use two time the `..._dnde_errp` column?

2022-07-20 15:05 UTC, adonath commented on gammapy/catalog/hawc.py
> +            * (np.abs(self.data["spec0_index_errp"]) + np.abs(self.data["spec0_index_errn"])),
If the catalog is reasonably formatted one `np.abs()` call should be sufficient, only for the quantity that is actually negative...

2022-07-21 11:01 UTC, registerrier approved these changes
Thanks @QRemy! Looks good.

2022-07-21 12:29 UTC, adonath approved these changes
Thanks @QRemy, no further comments from my side.

2022-07-21 12:30 UTC, merged