Allow to stack mask_fit in Dataset.stack
gammapy/gammapy pull request #4015
Opened 2022-06-30 10:11 UTC by QRemy

Allow to stack mask_fit in Dataset.stack in the same way than mask_safe

2022-07-20 14:35 UTC, adonath requested changes
Thanks @QRemy, I have left one inline suggestion. I think we should copy the other mask...

2022-07-20 14:35 UTC, adonath commented on gammapy/datasets/map.py
> +            self.mask_fit = other.mask_fit
```suggestion
            self.mask_fit = other.mask_fit.copy()
```

2022-07-22 14:06 UTC, registerrier approved these changes
Thanks @QRemy

2022-07-22 14:07 UTC, registerrier commented
@adonath comment has been taken into account. Merging now.

2022-07-22 14:07 UTC, merged