Fix bug on `TemporalModel.sample_time()`
gammapy/gammapy pull request #4067
Opened 2022-09-07 21:10 UTC by fabiopintore

This PR should fix a big in the `sample_time` function of `TemporalModel`, as reported in #4063 .

2022-09-08 16:12 UTC, adonath requested changes
Thanks @fabiopintore, this PR simplifies the implementation a lot! I have left two minor inline comments on the structure of the tests...

2022-09-08 16:12 UTC, adonath commented on gammapy/modeling/models/tests/test_temporal.py
> +    temporal_model = GaussianTemporalModel(t_ref=(time_ref.mjd) * u.d, sigma=sigma)
I think this could be split out as a separate test...

2022-09-08 16:12 UTC, adonath commented on gammapy/modeling/models/tests/test_temporal.py
> +    peak_time = light[1][np.argmax(light[0])]
As the light curve is Gaussian here, maybe check both: the mean and standard deviation?

2022-09-14 12:49 UTC, adonath approved these changes
Thanks @fabiopintore! No further comments from my side. Before merging we need a second review...

2022-09-14 13:06 UTC, registerrier approved these changes
Thanks @fabiopintore . This looks indeed much better!

I have no specific comment.

2022-09-14 13:15 UTC, merged

2022-09-14 13:15 UTC, adonath commented
Thanks @fabiopintore!