Add interp_scale to parameter scaling
gammapy/gammapy pull request #4218
Opened 2022-11-25 11:23 UTC by QRemy

Use the interpolation scale given by Parameter.interp in the transform from the parameter value to the factor seen by the optimizer, as proposed in #4027.
Not sure how to combine this with the scale method, for now I apply interp_scale first and then the scale method.

2022-12-09 17:01 UTC, adonath commented
Thanks @QRemy! Should deprecate the "old scaling" methods? @registerrier

2022-12-09 17:47 UTC, QRemy commented
For now they are still applied after the scaling from the .interp argument, not sure if it makes sense.

2023-01-25 01:42 UTC, adonath commented
@QRemy I think we never really discussed this PR in our dev call, would you mind setting it on the agenda for this Friday? https://github.com/gammapy/gammapy-meetings/tree/master/dev-meetings/2023/2023-01-27 Thanks!

2023-02-08 16:18 UTC, QRemy commented
For backward compatibility I added a `scale_interp="lin"` argument instead of using direclty `interp` so the transform is done correctly for previously written models.

2023-02-10 09:09 UTC, QRemy commented on gammapy/modeling/parameter.py
> +            self.value = float(value)
This looks like a bug, I will open PR to solve it separately.

2023-02-10 09:30 UTC, QRemy commented on gammapy/modeling/parameter.py
> +            self.value = float(value)
Done in #4324.

2023-09-26 15:06 UTC, bkhelifi commented
@QRemy what is the status of this work?

2023-12-20 17:02 UTC, QRemy commented on gammapy/modeling/parameter.py
> +        "reset sacling such as factor=value, scale=1"
```suggestion
        "reset scacling such as factor=value, scale=1"
```

2024-05-07 08:14 UTC, Astro-Kirsty commented
@QRemy, what is the status here?
Once rebased, ready for review?

2024-05-22 08:22 UTC, bkhelifi requested changes
Thanks a lot @QRemy. It seems more coherent now. I have just put some suggestions on the docstrings

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +    scale_interp : {"lin", "sqrt", "log"}
Can you profit of this PR to add in the docstring all the default values? Thanks

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +        "apply interpolation_scale and scale_method to the parameter"
```suggestion
        "Apply `interpolation_scale' and `scale_method' to the parameter."
```

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +        """update the parameter scale.
```suggestion
        """Update the parameter scale.
```

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +    def transform(self, value, update_scale=False):
What does exactly this function? Do not forget the default value of the argument

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +    def inverse_transform(self, factor):
What does exactly this function? A docstring might be great

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +        "reset scaling such as factor=value, scale=1"
```suggestion
        "Reset scaling such as factor=value, scale=1."
```

2024-05-22 08:22 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +        scale_method="scale10",
AS this class is exposed, it might be great to add a docstring describing it with its parameters (and default values)

2025-03-20 13:32 UTC, QRemy commented
Now the inverse transform of the covariance is implemented using `propagate` from `jacobi` package
So it's ready for review.

2025-03-20 13:32 UTC, QRemy commented on gammapy/modeling/parameter.py
> +    def inverse_transform(self, factor):
added

2025-03-20 13:32 UTC, QRemy commented on gammapy/modeling/parameter.py
> +    def transform(self, value, update_scale=False):
added

2025-03-20 13:35 UTC, QRemy commented on gammapy/modeling/parameter.py
> +        scale_method="scale10",
inherited from Parameter

2025-03-21 08:28 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +    def factor_min(self):
Per curiosity, for which purposes the two function factor_min and factor_max have been introduced? It seems not directly related to the PR topics

2025-04-17 13:46 UTC, QRemy commented
One last review before merging this old PR ?

2025-04-17 15:17 UTC, bkhelifi commented on gammapy/modeling/parameter.py
> +        scale_method="scale10",
This is really sad that this important class has no docstring... A reference to some tutorials could be also appreciated by users.
Even if it is not the scope of this PR, one could add that now OR make quickly an issue to update the documentation.

2025-04-17 15:21 UTC, bkhelifi submitted a review, later dismissed
OK for me, thanks @QRemy .
I have a comment on the docstring of the class ParameterPrior.

2025-04-17 21:40 UTC, registerrier reviewed
Thanks @QRemy. I have left some comments inline. 

My main comment is that this PR is introducing significant additional complexity, changes the serialization format of models and introduce an additional dependency (currently in all cases or you have to forbid setting the transform_scale to anything other than `"lin"` if `jacobi` is not installed).

Before merging, I think it would be important to clarify to what extent this PR brings a clear gain? In which use cases?  Can't priors produce similar results since changing the measure of a parameter must be equivalent to setting a prior?

2025-04-17 21:40 UTC, registerrier commented on gammapy/modeling/parameter.py
> +        This ``factor_max = transform(max)`` is for the optimizer interface.
For clarity, I would keep the previous definition and add the new one as most of the time transform is identity:
```
In general, when no transform is applied, ``factor_min = min / scale`` else ``factor_min = transform(min)``
```

2025-04-17 21:40 UTC, registerrier commented on gammapy/modeling/parameter.py
> +        self._scale = float(scale)
I must say that `Parameter` argument have become very complex. Is there a use case for a different scaling for scan and for parameter transform?
Is `scale_method` only relevant for `scale_transform=="lin"`?

2025-04-17 21:40 UTC, registerrier commented on gammapy/modeling/parameter.py
> +        factor = interp_scale(value)
I understand this is not the same `factor` as before, and I must say this is confusing when trying to understand the code.

2025-04-17 21:40 UTC, registerrier commented on gammapy/modeling/parameter.py
> +            self.update_scale(factor)
Does `update_scale` take the factor or the value in input?

2025-04-24 13:21 UTC, QRemy commented on gammapy/modeling/parameter.py
> +        self._scale = float(scale)
the scale can also be applied `scale_transform!="lin"` but I have no idea if this is useful.

2025-04-24 13:26 UTC, QRemy commented
> priors produce similar results since changing the measure of a parameter must be equivalent to setting a prior

priors change the likelihood while this change only how the parameter space is explored

2025-04-25 11:36 UTC, QRemy commented on setup.cfg
> +    jacobi
if we want to avoid new dependancy we could use the jacobian from scipy:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.differentiate.jacobian.html
and add in gammapy.utils a copy of the propagate method which is quite small:
https://github.com/HDembinski/jacobi/blob/main/src/jacobi/_propagate.py

2025-04-25 16:52 UTC, QRemy commented on gammapy/modeling/parameter.py
> +    def scale_transform(self, val):
removed jacobi

2025-04-25 16:53 UTC, QRemy commented on setup.cfg
> +    jacobi
removed jacobi and now the derivative are computed analytically

2025-04-27 04:55 UTC, QRemy commented on gammapy/modeling/parameter.py
> +        factor = interp_scale(value)
renamed transformed

2025-05-09 10:41 UTC, bkhelifi commented
What is the status here, @QRemy ?

2025-05-09 11:52 UTC, QRemy commented
> What is the status here, @QRemy ?

Ready

2025-05-13 09:24 UTC, registerrier approved these changes
Thanks @Qremy . Looks good. No further comments.

Since the commits are spread over a long period, isn't it beter for the git history here to squash and merge?

2025-05-13 09:27 UTC, QRemy commented
> Since the commits are spread over a long period, isn't it beter for the git history here to squash and merge?

not sure about that I think we can just merge it like this.

2025-05-13 09:38 UTC, registerrier commented
> > Since the commits are spread over a long period, isn't it beter for the git history here to squash and merge?
> 
> not sure about that I think we can just merge it like this.

OK Let's make a simple merge once the CI is finished.

2025-05-13 10:09 UTC, merged