Fix latex rendering in tutorial
gammapy/gammapy pull request #4300
Opened 2023-01-30 15:17 UTC by AtreyeeS

Minor typo

2023-02-01 13:31 UTC, QRemy requested changes
Thanks @AtreyeeS, I added a suggestion to fix a typo.

2023-02-01 13:31 UTC, QRemy commented on examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
> +:math:`:math:`\\theta` cut). In this notebook we will focus on how to perform a
This line does not match the other changes, `:math: seems repeated

```suggestion
:math:`\\theta` cut). In this notebook we will focus on how to perform a
```

2023-02-07 11:26 UTC, registerrier approved these changes
Thanks @AtreyeeS !

2023-02-07 11:26 UTC, registerrier commented
CI fail is unrelated. Merging.

2023-02-07 11:26 UTC, merged