Use interpolation for dark matter mass
gammapy/gammapy pull request #4785
Opened 2023-10-06 15:39 UTC by StFroese

Fixes #4781 

The `PrimaryFlux` is now based on `TemplateNDSpectralModel`. My upper limit plot look better now haha :shipit: 

Before:
<img width="810" alt="272549014-0be46766-b6d0-48dc-9372-8acc16eb342d" src="https://github.com/gammapy/gammapy/assets/44728015/0218fb88-e47e-4c8a-9351-6554ae1c9f6d">

After:
<img width="671" alt="Screenshot 2023-10-06 at 16 39 19" src="https://github.com/gammapy/gammapy/assets/44728015/dec54ff7-786e-48d1-8036-55bcb39b9f2f">

2023-10-06 16:07 UTC, StFroese commented
@adonath can you review? :)

2023-10-06 16:36 UTC, adonath requested changes
Thanks @StFroese, this looks very good! I left one comment with regards to backwards compatibility.

2023-10-06 16:36 UTC, adonath commented on gammapy/astro/darkmatter/spectra.py
> -    def table_model(self):
Please keep this method for backwards compatibility. We have to deprecate it for 1-2 minor version before we can remove it. See https://docs.gammapy.org/1.1/development/dev_howto.html?highlight=deprecation#how-to-handle-api-breaking-changes

2023-10-09 15:12 UTC, adonath requested changes
Thanks @StFroese! One last comment from my side: please add a "regression test", this means a test, that would fail for nearest-neighbor interpolation (as it was before) and now passed correctly. Just evaluating the model on a 2-3 values and asserting the results is fine.

2023-10-10 13:02 UTC, adonath approved these changes
Thanks @StFroese! I left some inline edits to merge...otherwise this is ready now from my side!

2023-10-10 13:02 UTC, adonath commented on gammapy/astro/darkmatter/spectra.py
> +        super().__init__(regionMap)
```suggestion
        super().__init__(region_map)
```

2023-10-10 13:02 UTC, adonath commented on gammapy/astro/darkmatter/spectra.py
> +        region = CircleSkyRegion(coord, radius=1 * u.deg)
```suggestion
```

2023-10-10 13:02 UTC, adonath commented on gammapy/astro/darkmatter/spectra.py
> +            region, axes=[log10x_axis, mass_axis], data=self.table[channel_name]
```suggestion
            region=None, axes=[log10x_axis, mass_axis], data=self.table[channel_name]
```

2023-10-10 13:52 UTC, adonath approved these changes
Thanks, I have no further comments! 

@registerrier or @QRemy please provide a 2nd review...

2023-10-10 14:43 UTC, registerrier submitted a review, later dismissed
Thanks @StFroese . This looks good!

Maybe one general question regarding extrapolation. Should it be allowed by default (as is the case here) or should it be forbidden?

2023-10-10 14:43 UTC, registerrier commented on gammapy/astro/darkmatter/spectra.py
> +        Dark matter mass
While this may be obvious, it could be worth to mention that the mass is given as rest mass energy (ie m c^2)

2023-10-10 17:27 UTC, registerrier commented
> @registerrier I haven't thought about that and my first thought is to not allow it since we don't know if it's possible

I suppose that extrapolation in `mDM` should be avoided, but they are necessary in `log10x` since you might want to estimate the flux above the DM particle mass.
So probably this requires a check on the `mDM` setter but we cannot enforce `axtrapolate=False`.

2023-10-11 12:50 UTC, StFroese commented
@registerrier yes I agree. I will check if `mDM` is out of range

2023-10-13 16:09 UTC, registerrier approved these changes
Thanks @StFroese . This looks good!

2023-10-13 16:10 UTC, merged