Example in docstring of `select_nested_models`
gammapy/gammapy pull request #4961
Opened 2023-12-06 15:59 UTC by Astro-Kirsty

**Description**
This PR is to include an example in the docstring of `select_nested_models`. To resolve #4788

For now I think this is enough to allow users to know how the function can be utilised.
At a later stage we can create a tutorial once some further features have been implemented by @QRemy. 

Note: I also adapted one line in `gammapy.utils.parallel.multiprocessing_manager` to fix the docs.

2023-12-06 16:12 UTC, QRemy requested changes
Thanks @Astro-Kirsty, I have just one comment :

2023-12-07 10:00 UTC, QRemy commented on gammapy/modeling/selection.py
> +        model = SkyModel.create(spectral_model="ecpl", spatial_model="point", name='hess')
```suggestion
        model = SkyModel.create(spectral_model="ecpl", spatial_model="point", name='hess')
        model.spatial_model.freeze()
        n_free_parameters = len(model.parameters.free_parameters)
```

2023-12-08 12:32 UTC, QRemy approved these changes
Thanks @Astro-Kirsty, no further comment.

2023-12-08 12:46 UTC, registerrier approved these changes
Thanks @Astro-Kirsty . Are you sure this goes through doctest this way?

2023-12-08 12:46 UTC, registerrier commented on gammapy/modeling/selection.py
> +    ::
```suggestion
    .. testcode::
```

2023-12-08 16:37 UTC, merged