Add and adjust tests
gammapy/gammapy pull request #4985
Opened 2023-12-13 17:00 UTC by Astro-Kirsty

**Description**
This pull request removes some `TODO` from tests which are not needed and addresses others by adding further tests.

2023-12-14 16:19 UTC, Astro-Kirsty commented
I don't understand why this test is failing. I import naima in the same fashion as `modeling.models.tests.test_spectral.py`

2023-12-15 12:37 UTC, QRemy requested changes
Thanks @Astro-Kirsty, the fails are related to a missing dependency :

2023-12-15 12:37 UTC, QRemy commented on gammapy/modeling/models/tests/test_io.py
> +    import naima
Here it would be better to have a separate test for the Naima moldel creation with the decorator @requires_dependency("naima")

2023-12-17 12:29 UTC, QRemy approved these changes
Thanks @Astro-Kirsty, no further comment.

2023-12-18 11:45 UTC, registerrier submitted a review, later dismissed
Thanks @Astro-Kirsty . Looks good . Two minor suggestions.

2023-12-18 11:45 UTC, registerrier commented on gammapy/maps/hpx/tests/test_ndmap.py
> +    assert_allclose(m, m2, atol=1e-4)
```suggestion
    assert m.geom.is_allclose(m2.geom)
```

2023-12-18 11:45 UTC, registerrier commented on gammapy/maps/hpx/tests/test_ndmap.py
> +    assert_allclose(m, m2, atol=1e-4)
```suggestion
    assert  m.geom.is_allclose(m2)
```

2023-12-18 11:47 UTC, registerrier commented on gammapy/maps/hpx/tests/test_ndmap.py
> +    assert_allclose(m.data, m2.data, atol=1e-4)
```suggestion
    assert m.is_allclose(m2)
```

2023-12-18 11:47 UTC, registerrier commented on gammapy/maps/hpx/tests/test_ndmap.py
> +    assert_allclose(m.data, m2.data, atol=1e-4)
```suggestion
    assert m.is_allclose(m2.data)
```

2023-12-18 12:10 UTC, registerrier commented on gammapy/maps/hpx/tests/test_ndmap.py
> +    assert  m.geom.is_allclose(m2)
```suggestion
    assert m.geom.is_allclose(m2.geom)
```

2023-12-19 11:57 UTC, merged