Add function to scale colorbar height
gammapy/gammapy pull request #5055
Opened 2024-01-29 16:55 UTC by Astro-Kirsty

**Description**
 This PR is to resolve #4052

The [suggestion](https://github.com/gammapy/gammapy/issues/4052#issuecomment-1235445757) by Axel did not work for the `plt.tight_layout()` in the `peek` methods, even with `use_gridspec` set to `True`. So I had to find another possibility.

Instead, I utilised the `make_axes_locatable` functionality in the [mpl_toolkits](https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_with_axes_divider.html) of matplotlib.

**Note**: `divider = make_axes_locatable(ax)` makes them the same as the ax
`size` is a percentage of the main axis width to be set as the cbar width
`pad` is similarly determined as the percentage of the main axes width to pad by

2024-01-29 17:59 UTC, bkhelifi submitted a review, later dismissed
So amazing!!!! Thanks a lot @Astro-Kirsty

2024-01-29 19:30 UTC, adonath commented on gammapy/visualization/utils.py
> +        img, cax=cax, orientation="vertical", use_gridspec=True, label=label
Maybe just forward the keywords `**kwargs` to `plt.colorbar()`?

2024-01-29 19:32 UTC, adonath commented on gammapy/visualization/utils.py
> +    cax = divider.append_axes(position="right", size="5%", pad="2%")
One could introduce an argument `axes_loc={}` with the keywords for this method, such that users can modify it. The defaults can best set using `axes_loc.setdefult()`. But keeping the hard-coded values is probably also fine.

2024-01-29 19:33 UTC, adonath reviewed
Thanks @Astro-Kirsty, I left some minor comments, otherwise look good!

2024-01-30 14:29 UTC, Astro-Kirsty commented on gammapy/irf/effective_area.py
> +    ):
Probably wise, I'll implement it

2024-01-30 14:30 UTC, bkhelifi commented on gammapy/irf/background.py
> +    ):
Same comment about the docstring...

2024-01-31 10:21 UTC, bkhelifi submitted a review, later dismissed
Thanks a lot @Astro-Kirsty! All good for me

2024-01-31 11:05 UTC, registerrier requested changes
Thanks @Astro-Kirsty . 
This PR misses tests. If you explicitly use some matplotlib functionalities, they should be tested. Otherwise we could see failures appearing if the syntax is changed in matplotlib.

Maybe an example usage might be of help in docstrings.

2024-02-01 07:41 UTC, registerrier submitted a review, later dismissed
Thanks @Astro-Kirsty . No further comment from my side. 

In general, I think the approach of helper function to add configuration to the plots might be a good option. e.g. one could have used only the `add_colorbar` function to add the required functionality instead of adding the `axes_loc` argument to `plot` methods. 

In the long run, a general configuration and/or context managers to do this kind of things might be the way to go.

2024-02-01 07:55 UTC, registerrier commented
Can you rebase @Astro-Kirsty ?

2024-02-01 09:01 UTC, Astro-Kirsty commented
Thanks @registerrier. 
I have rebased

2024-02-01 10:38 UTC, bkhelifi submitted a review, later dismissed
Thank you very much!

2024-02-01 10:47 UTC, Astro-Kirsty commented
This is not ready for merge, I am solving the error in CI and also the colorbar when we have WCS axes

2024-02-01 11:52 UTC, Astro-Kirsty commented
Should be all good now!

2024-02-01 14:16 UTC, registerrier approved these changes
Thanks @Astro-Kirsty . No further comments.

2024-02-01 14:16 UTC, merged