Add boundary condition to create a PeriodicMapAxis
gammapy/gammapy pull request #5169
Opened 2024-03-13 14:56 UTC by AtreyeeS

This PR adds a PeriodicMapAxis.
Its rather simple, only one function, so arguably it does not need its own class at all.
But I think its conceptually simpler to have a separate name for such an axis.
It can be useful for phase analysis, or for asymmetric IRFs defined not in (Lon, lat) but (offset, theta), as brought up in one of the CTAC ASWG calls...

2024-03-15 10:40 UTC, MRegeard approved these changes
Thanks @AtreyeeS, this is a great feature

2024-03-15 10:45 UTC, MRegeard commented
On top of that, an idea that we could add following this feature is a method on maps to offset the data that are indexed through a periodic axis. This is usual in pulsar analysis to put the peak of the pulsar that would be around 0 (or 1) at the center of the phasogram.

2024-03-28 09:37 UTC, bkhelifi commented on gammapy/maps/tests/test_axes.py
> +    assert_allclose(axis1.wrap_coords(coords), [0.0, 0.3, 0.1, 0.2], rtol=1e-5)
A naive question.. the nodes of the final axis are not crescent?

2024-05-02 14:07 UTC, AtreyeeS commented
I created an option on `MapAxis` as `boundary_type` to specify the boundary condition.
This still assumes that the edges wrap, or should that be configurable?

2024-05-06 15:18 UTC, QRemy reviewed
Thanks @AtreyeeS,  looks good, I made some change to remove the private functions.

2024-05-06 15:18 UTC, QRemy commented on gammapy/maps/axes.py
> +    def _coord_to_pix(self, coord):
I don't think that the private definition is necessary here

2024-05-06 15:18 UTC, QRemy commented on gammapy/maps/axes.py
> +    def _wrap_coords(self, coords):
could be public

2024-05-06 15:18 UTC, QRemy commented on gammapy/maps/axes.py
> +    def _coord_to_idx(self, coord, clip=False):
same

2024-05-06 20:34 UTC, adonath requested changes
Thanks @AtreyeeS and @QRemy! I have left some minor comment to clean up the implementation...

2024-05-07 15:45 UTC, QRemy commented
Thanks @adonath for the suggestions I implemented them and I will merge this once the CI pass if no objection.

2024-05-07 16:21 UTC, QRemy commented on gammapy/maps/axes.py
> +        if boundary_type not in available_boundary:
added

2024-05-07 18:15 UTC, merged