Add a time_reference arguments to `_template_model_from_cta_sdc`
gammapy/gammapy pull request #5204
Opened 2024-04-08 10:00 UTC by fabiopintore

This PR adds a reference time argument to the function `gammapy.modeling.model.utils._template_model_from_cta_sdc`. This can be useful in the cases when a given SDC model has to have a specific reference time (e.g. flaring sources) and not a generic one.

2024-04-08 13:04 UTC, registerrier requested changes
Thanks @fabiopintore . I have left few comments inline.

2024-04-08 13:04 UTC, registerrier commented on gammapy/modeling/models/tests/test_utils.py
> +def test__template_model_from_cta_sdc_reference_time():
This misses a `@requires_data()`

2024-04-08 13:04 UTC, registerrier commented on gammapy/modeling/models/utils.py
> +        if t_ref:
Here you could use `gammapy.utils.time.time_ref_to_dict`

2024-04-09 15:16 UTC, registerrier approved these changes
Thanks @fabiopintore . Looks good to me.

2024-04-10 08:18 UTC, AtreyeeS approved these changes
Thanks @fabiopintore !

2024-04-10 21:23 UTC, merged