Allow `MapAxis` to be passed in `SpectralModel.plot()`
gammapy/gammapy pull request #5222
Opened 2024-04-19 12:14 UTC by Astro-Kirsty

This PR resolves #5171

We can now accept a `MapAxis` for spectral plotting both in `plot` and `plot_error`.

Note: `if energy_bounds is not None:` must be used rather just `if energy_bounds` due to the quantity handling in [astropy](https://github.com/astropy/astropy/pull/14124).

2024-04-19 17:29 UTC, bkhelifi requested changes
Thanks @Astro-Kirsty ... I have just some comments on the docstrings.

2024-04-19 17:29 UTC, bkhelifi commented on gammapy/modeling/models/spectral.py
> +            Plot energy bounds passed to `~gammapy.maps.MapAxis.from_energy_bounds`.
The description with  gammapy.maps.MapAxis.from_energy_bounds is very technical and only experts can understand...
Also you have not mentioned the default values

2024-04-19 17:29 UTC, bkhelifi commented on gammapy/modeling/models/spectral.py
> +        if energy_bounds is not None:
If both are defined, which one to use? Why the priority is given to energy_bounds?

2024-04-19 17:29 UTC, bkhelifi commented on gammapy/modeling/models/spectral.py
> +        energy_axis : `~gammapy.maps.MapAxis`
See my comment above

2024-04-20 07:00 UTC, AtreyeeS reviewed
Thanks @Astro-Kirsty ! 
My main comment is that `energy_axis` should be given priority over `energy_bounds`. Also, to reduce the code duplication between `plot` and `plot_error`, maybe you can create a small hidden function `_get_axis_for_plot` and move the common code you introduced.

2024-04-22 07:36 UTC, registerrier reviewed
Thanks @Astro-Kirsty . 

If there are two possible exclusive arguments, the default behavior should be to fail if both are defined.
Note the change modifies makes all arguments optional  and modify their order. This is an API breaking change.

Another option could be to let `energy_bounds` be either a `MapAxis` or a two valued energy `Quantity`. In itself, `energy_bounds` does not tell much about its type.

2024-04-22 15:21 UTC, Astro-Kirsty commented
> Another option could be to let `energy_bounds` be either a `MapAxis` or a two valued energy `Quantity`. In itself, `energy_bounds` does not tell much about its type.

I think this could be a good idea. Do others have an opinion? @AtreyeeS @bkhelifi

2024-04-29 13:20 UTC, Astro-Kirsty commented
Updated the PR to allow for different types in the energy_bounds rather than another keyword as per discussions in the dev call last Friday

2024-05-03 16:36 UTC, bkhelifi commented on gammapy/modeling/models/spectral.py
> +        If ``energy_bounds`` is supplied as a tuple or Quantity, an ``energy_axis`` is created internally with
Or a list also;)

2024-05-03 16:38 UTC, bkhelifi submitted a review, later dismissed
Thanks a lot @Astro-Kirsty ... Looks ready to be merged!

2024-05-06 12:08 UTC, QRemy approved these changes
Thanks @Astro-Kirsty, looks good I have only minor style comments.

2024-05-06 12:08 UTC, QRemy commented on gammapy/modeling/models/spectral.py
> +            or isinstance(energy_bounds, list)
```suggestion
            isinstance(energy_bounds, (tuple, list, Quantity))
```

2024-05-06 12:08 UTC, QRemy commented on gammapy/modeling/models/spectral.py
> +            or isinstance(energy_bounds, list)
```suggestion
            isinstance(energy_bounds, (tuple, list, Quantity))
```

2024-05-06 12:22 UTC, bkhelifi approved these changes
All good!

2024-05-06 13:05 UTC, merged