Coherent units in `TemporalModel.sample_time`
gammapy/gammapy pull request #5298
Opened 2024-06-11 09:09 UTC by fabiopintore

This is a very minimal fix to preserve units coherence in the `TemporalModel.sample_time`. 

The time sampling is indeed performed over a number of time bins which is calculated internally on the basis of the `ontime` and the `t_delta`. 
In the current version, the `ontime` is calculated in seconds but it takes the units from `t_delta`. The latter is by default in seconds, but it can be passed by the user. 
If the units of `ontime` and `t_delta` are not consistent, this introduces an issue.

2024-06-14 09:11 UTC, bkhelifi approved these changes

2024-06-14 10:22 UTC, registerrier requested changes
Thanks @fabiopintore . I think it would be simpler to convert the `TimeDelta` to a Quantity in seconds.

2024-06-14 10:22 UTC, registerrier commented on gammapy/modeling/models/temporal.py
> +        ontime = u.Quantity((t_max - t_min).sec, t_delta.to("s").unit)
```suggestion
        ontime = (t_max - t_min).to("s")
```

2024-06-18 10:26 UTC, cgalelli approved these changes
Thanks @fabiopintore . An alternative solution could be to use .decompose() but this is completely fine (and probably more efficient)

2024-06-19 17:28 UTC, QRemy approved these changes
Thanks @fabiopintore, no comment from my side.

2024-06-19 18:34 UTC, merged

2024-06-20 14:58 UTC, QRemy commented
Backport to 1.0.x is not needed the code has correct a unit `ontime = u.Quantity((t_max - t_min).sec, "s")`