Set a diagonal Edisp when `MapDataset.edisp` is `None`
gammapy/gammapy pull request #5308
Opened 2024-06-13 09:36 UTC by fabiopintore

This PR should fix the issue #5274.
It introduces the possibility to create a diagonal edisp matrix when the `dataset` does not have one. This will avoid that `Fit` and `FluxPointsEstimator ` will fail when the edisp is not defined.
Tests have been updated accordingly.

2024-06-14 08:08 UTC, AtreyeeS submitted a review, later dismissed
Thanks @fabiopintore ! Very small comments inline

2024-06-14 08:08 UTC, AtreyeeS commented on gammapy/datasets/tests/test_map.py
> +    #    assert "Edisp is not defined. A diagonal response matrix will be set." in [record.levelname for record in caplog.records]
Why did you comment this?

2024-06-14 08:08 UTC, AtreyeeS commented on gammapy/datasets/tests/test_spectrum.py
>      assert dataset_new.name == "test"
maybe add `dataset_new.edisp is not None`

2024-06-14 08:56 UTC, bkhelifi requested changes

2024-06-14 08:56 UTC, bkhelifi commented on gammapy/datasets/tests/test_spectrum.py
> +    print(actual)
remove the print

2024-06-14 09:35 UTC, MRegeard commented
Thanks @fabiopintore. I am wondering wether the edisp code in the `__init__` function should go in a setter. It would make the `__init__` simpler and also ensure type check when setting an edisp after instantiation. 
I would also add a comment in the docstring that specify behaviour when edisp is None (in addition to the warning raised), so that it is transparent to doc readers.

2024-06-20 10:57 UTC, bkhelifi commented
Creating a default edisp when nothing is precised looks strange for me: if someone forgets to set an edisp, it should realize with a crash.... If someone wants a diagonal edisp, it can not it easly.
This fix for the FluxPointsEstimator migh be dangeourous for the Data Reduction step... I am wondering whether one should not add a diagonal matrix if edisp is None inside the FluxPointsEstimator. Any opinion?

2024-06-21 10:17 UTC, QRemy commented
> @bkhelifi : The issue is that in the current implementation, `MapEvaluator` silently creates a diagonal edisp in case no `edisp` is present, and, if `e_true = e_reco` the fit proceeds normally and a very confusing error is raised during the flux estimation. This PR makes the process cleaner and consistently warns the user about diagonal edisp creation.
> 

In principle the `MapEvaluator` silently creates a diagonal edisp only if model.apply_irf["edisp"]==False

2024-06-21 10:21 UTC, AtreyeeS commented
> In principle the MapEvaluator silently creates a diagonal edisp only if model.apply_irf["edisp"]==False

But the fit still works if `energy_true = energy_reco` , model.apply_irf["edisp"]==True and `dataset.edisp=None`
I think getting this case to fail with a `ValueError(model.apply_irf["edisp"] is True but no edisp set on dataset)` is also an acceptable solution

2024-06-23 16:57 UTC, AtreyeeS commented
Super seeded by https://github.com/gammapy/gammapy/pull/5342

2024-06-23 16:57 UTC, closed without merging