Introduce context manager to set energy range to mask fit
gammapy/gammapy pull request #5387
Opened 2024-07-22 21:16 UTC by registerrier

**Description**

This pull request introduces a context manager to set an energy range to the mask fit of a `Datasets` object. This is meant to replace the `Datasets.split_by_energy` method that `FluxPointsEstimator` is using. An advantage of this approach is to avoid building new evaluators for energy energy band. It is not clear it is sufficient to support multiprocessing though. 

Opinions @QRemy , @AtreyeeS , @adonath ?

Note that some code duplication can be further removed with the `create_energy_mask` method (namely the group table creation is also used in `Dataset.split_by_energy`)

**Dear reviewer**

2024-07-23 09:54 UTC, QRemy requested changes
Thanks @registerrier, this could also be attached to the datasets together with models.restore_status: 

```
    @contextmanager
    def set_and_restore_status(self, energy_min=None, energy_max=None, restore_values=True):
        with self.models.restore_status(restore_values) as restore_models, set_and_restore_mask_fit(self, energy_min, energy_max) as restore_mask:
            yield (restore_models, restore_mask)

```

2024-07-23 09:54 UTC, QRemy commented on gammapy/datasets/utils.py
> +                mask_fit *= dataset.mask_fit
this could go in `create_energy_mask`

2024-07-23 12:09 UTC, adonath commented
Thanks @registerrier! I just wanted to add some context to this change: the reason why we decided to split the datasets was indeed performance. So evaluating a set of smaller dataset was faster than evaluating and masking the whole dataset. However it seems with all the caching of predicted counts and modifications of the `MapEvaluator` that we have introduced since this is not the case anymore and the model set-up became the bottleneck.

That being said, I think the context manager is a useful addition from the user side as well.

2024-07-23 12:18 UTC, VascoSch92 commented on gammapy/datasets/utils.py
> +    is_normal = group["bin_type"] == "normal   "
just to be sure: is it normal that you have 3 spaces after normal :-) ???

2024-08-01 09:44 UTC, MRegeard commented
Thanks @registerrier, it is a nice feature. However, I think it has to be exposed in tutorials, otherwise it will not be used a lot. Also adding an example in the docstring might help. 
I was also wondering why we prefer defining a class context manager over using contextlib ?

2024-08-01 16:06 UTC, bkhelifi commented
If a central "class context manager" is introduced, there are many features that could be added:
- logging level
- progress bar
- color-blind switch
- general multiprocessing options
- MD5 checks or writing
- maybe later some stuff associated to metadata
- maybe a switch of the FoValignement axes (#4667)
- AOB
And its representation into the HLI.

This obviously goes beyond this PR... It depends on what means 'context manager'.

2025-03-07 18:06 UTC, registerrier commented on gammapy/datasets/utils.py
> +    def __init__(self, datasets, energy_min, energy_max):
Well, if we are to impose a consistent mask for all dataset we should specify energy range. Otherwise different datasets might different energy ranges.

2025-03-07 18:07 UTC, registerrier commented on gammapy/datasets/utils.py
> +        datasets = Datasets()
Done

2025-05-28 16:10 UTC, QRemy commented
@registerrier 

I simplified it to avoid introducing `create_energy_mask`  and using `dataset._geom.energy_mask` directly (if used with round_to_edge=True it should produce the same behaviour).

Also added the possibility to provide directly a `mask_fit` so this can be used for 3d masks.

2025-06-27 11:13 UTC, registerrier reviewed
Thanks for the changes @QRemy . Looks good to me

2025-06-27 11:14 UTC, merged