Add alpha maps to `ExcessMapEstimator`
gammapy/gammapy pull request #5408
Opened 2024-08-01 10:30 UTC by Astro-Kirsty

This resolves #5247.
The general idea is that we sometime want access to the correlated on and off and alpha values. We currently only handle these values within `convolved_map_dataset_counts_statistics`. The idea is to create a `Maps` object that is a dictionary of maps containing the required maps. Then if the `full_output` option is selected it will create the maps, provided that a `MapDatasetOnOff` is provided.
This was one idea of implementation that @registerrier and I discussed. 
I think this seems like the easiest way that won't break API.  Because we just have the default `full_output=False`, which is as it was before.

2024-08-01 12:32 UTC, adonath commented
Thanks a lot @Astro-Kirsty! One question first: have you discussed the option with @registerrier to make theses maps just part of `FluxMaps`?

2024-08-01 13:18 UTC, Astro-Kirsty commented
That is another option we discussed, to include them as user option in the `selection_optional`! 
Open to opinions on what we think is best

2024-08-01 13:24 UTC, QRemy requested changes
Thanks @Astro-Kirsty, my proposal would be to add alpha in `selection_optional` and to have it also as an optional  entry in the flux maps. Then to avoid having two outputs in `convolved_map_dataset_counts_statistics`  it could be splited in two functions as in the comment below :

2024-08-01 13:24 UTC, QRemy commented on gammapy/estimators/map/excess.py
> +            )
maybe introduce a private function get_convolved_maps(dataset, kernel, mask, correlate_off) that returns a dict of `convolved_maps` and use it in `convolved_map_dataset_counts_statistics(convolved_maps, staty_type=dataset.stat_type)` (it is not part of the public api so it think it is fine to change its arguments).
Then in `estimate_excess_map` you add `if alpha in selection_optional : maps['alpha']=...`

2024-08-01 13:35 UTC, adonath commented
I'm with @QRemy here, just add them as optional selection and data members to `FluxMaps`, this way we achieve a more consistent and convenient API.

I think changing the return type based on configuration / input to a function is an anti pattern in programming. It typically leads to more code complexity later. It is much better to stick with dictionary like output classes with optional quantities.

2024-08-01 14:59 UTC, Astro-Kirsty commented
Okay, thanks for the input. I will adapt the code accordingly

2024-08-01 16:23 UTC, Astro-Kirsty commented
I've made the adaptions @adonath and @QRemy. 
I still need to create proper tests, and make sure docstrings are good, but thought you could give your general thoughts?

Also tests will fail for `selection_optional=["all"]` because we can only calculate the new parameters if there it is a `MapDatasetOnOff`. Not certain how we want to proceed there, have empty maps for that option when MapDataset or the 'all' option doesn't select those ones

2024-08-02 07:42 UTC, QRemy commented on gammapy/estimators/map/excess.py
> +        for correlated on, correlated off and alpha. Default is False.
```suggestion
```
No longer needed

2024-08-02 07:42 UTC, QRemy commented on gammapy/estimators/map/excess.py
> +        full_output=False,
```suggestion
```

2024-08-02 07:42 UTC, QRemy commented on gammapy/estimators/map/excess.py
> +        self.full_output = full_output
```suggestion
```
```suggestion
```

2024-08-02 07:56 UTC, QRemy commented on gammapy/estimators/map/excess.py
> +                    maps["acceptance_off"] = convolved_maps["acceptance_off"]
```suggestion
            if isinstance(dataset, MapDatasetOnOff):
                keys_onoff = set(["alpha", "acceptance_on", "acceptance_off"])
                for key in keys_onoff.intersection(self.selection_optional):
                    maps[key] = convolved_maps[key]
```

Here I think we can avoid silently ignore the keys that are not applicable to the `MapDaset` as long as the docstring states clearly that alpha is available only for the  `MapDatasetOnOff`.

2024-08-02 08:00 UTC, QRemy reviewed
Thanks @Astro-Kirsty, I made some simplifications.
In particular I think we can silently ignore the keys that are not applicable to the MapDaset as long as the docstring states clearly that alpha is available only for the MapDatasetOnOff.

2024-08-02 09:33 UTC, QRemy commented on gammapy/estimators/map/excess.py
> +        Default is None so the optional steps are not executed.2
```suggestion
        Default is None so the optional steps are not executed.
```

2024-08-02 09:34 UTC, QRemy commented on gammapy/estimators/map/core.py
> +        * acceptance_on : optional, acceptance from the oon region
```suggestion
        * acceptance_on : optional, acceptance from the on region
```

2024-08-02 14:03 UTC, QRemy approved these changes
Thanks @Astro-Kirsty, no further comment.

2024-08-02 15:15 UTC, AtreyeeS approved these changes
Thanks @Astro-Kirsty ! No comments

2024-08-02 16:44 UTC, merged