Include further keywords in `codemeta.json`
gammapy/gammapy pull request #5434
Opened 2024-09-16 09:25 UTC by Astro-Kirsty

This resolves #4617 and related to #5095

Most of the keywords we want to add can be directly to the `json` file as they will not change across different versions. Do we actually need anything else defined in the `codemeta.py` if is the same across versions?
- Not sure about the `runtimePlatform`?
- In v1.0 we had: dateCreated", "datePublished" and "dateModified". But now we do not use "dateModified", how do we want to proceed?

2024-09-16 11:22 UTC, cgalelli commented on codemeta.json
> +    "applicationSubCategory": "Very-high energy gamma rays",
Any possibility of being more broad here? e.g. HE gamma rays, VHE gamma rays, neutrino physics etc

2024-09-20 07:59 UTC, registerrier reviewed
Thanks @Astro-Kirsty . 
The json file is updated on the fly by the codemeta.py script. The idea is rather to adapt the script to include necessary changes, in particular the dates that have to be updated at the time of the release.

2024-09-20 12:54 UTC, Astro-Kirsty commented
Okay @registerrier, but some of these are defined within the python file. For example, the key words. Is that because the file was edited afterwards and I should add anything that is missing? Or do I misunderstand something

2024-10-01 18:01 UTC, bkhelifi requested changes
Thanks a lot @Astro-Kirsty. I have some minor comments

2024-10-02 13:25 UTC, bkhelifi approved these changes
Thanks a lot!

2024-10-03 13:48 UTC, registerrier approved these changes
Thanks @Astro-Kirsty . Looks good.

I think the definition of publication date is a bit unclear in the codemeta specifications (since the parameter is associated to different versions). I would rather have e.g. the date of last LTS, which, I think, is more relevant than that of v0.1. Opinion @bkhelifi @adonath ?

2024-10-04 15:17 UTC, registerrier commented
Merging now. We will see if further changes are needed in another PR.

2024-10-04 15:18 UTC, merged

2024-10-07 21:39 UTC, vuillaut commented
> > Thanks @Astro-Kirsty . Looks good.
> > I think the definition of publication date is a bit unclear in the codemeta specifications (since the parameter is associated to different versions). I would rather have e.g. the date of last LTS, which, I think, is more relevant than that of v0.1. Opinion @bkhelifi @adonath ?
> 
> Not strongly! each release is a publication... But there are issues about that on which @vuillaut has worked: https://gitlab.in2p3.fr/escape2020/wp3/eossr/-/issues/13 and [codemeta/codemeta#285](https://github.com/codemeta/codemeta/pull/285). What do you recommand @vuillaut ? the date of the release (ie `time.now()`)?

Hi
I would recommend the date of the release but you could make a different choice that is more relevant to gammapy.

Concerning the keywords, I'd recommend you use the ones from https://astrothesaurus.org/ that has the advantage to be used across different services (but again, there is nothing *wrong* using a different vocabulary).