WcsNDMap.downsample normalization issue fix
gammapy/gammapy pull request #5508
Opened 2024-10-17 15:18 UTC by k-egg

**Description**

This pull request fixes #5493. Instead of specifying either `np.nansum` or `np.nanmean` as functions for `block_reduce`, `self.data * weights` is now always summed and afterwards divided by the sum of the weights. This way the weighted average is calculated correctly.

**Dear reviewer**

This pull request is ready for review! Please let me know if anything should be changed or I missed anything. Thank you!

2024-11-08 18:04 UTC, adonath commented
Please check the comment here for an alternative suggestion https://github.com/gammapy/gammapy/issues/5493#issuecomment-2465313896

2025-02-07 15:10 UTC, registerrier requested changes
Thanks @k-egg . Having a test is important.

I would just ask you to make a simpler test. As is it is difficult to read and understand if after some it comes to fail because of a code change.
I would suggest to test the weighted downsample in a separate test function. You don't need to apply the full parameterized list of geometries but simply build a small one in the test and assert on explicit numerical values.

2025-02-07 15:10 UTC, registerrier commented on gammapy/maps/wcs/tests/test_ndmap.py
> +                ),
This is too complex and impossible to debug if the test would come to fail. Again with a simple predefined geometry with a defined (not random) weights array you can directly compare to specific value in your downsampled map.

2025-02-10 13:11 UTC, k-egg commented on gammapy/maps/wcs/tests/test_ndmap.py
> +        if len(m.data.shape) == 3:
Hi Regis, thanks for your feedback, I've implemented a much simpler test.

2025-02-13 09:43 UTC, registerrier approved these changes
Thanks @k-egg . This looks good to me.

2025-02-13 09:44 UTC, merged