Use `ctao_south` and `ctao_north` in observatory locations defined in Gammapy
gammapy/gammapy pull request #5513
Opened 2024-10-21 11:06 UTC by morcuended

**Description**

This PR is to addresses #5501. 

**Dear reviewer**

@bkhelifi, regarding the log info message, should it go inside the definition of the `observatory_locations` dictionary? Maybe using `@deprecated_renamed_argument`?

2024-10-22 10:49 UTC, bkhelifi submitted a review, later dismissed
It looks good for me! Thanks a lot

2024-10-22 15:18 UTC, morcuended commented
> a warning and internally overload the parameter to ctao-north such that the code continues to run

To be able to do this I propose creating a class that handles the deprecation warning. Let me know your opinions. I'll add a test for this deprecation warning as well.

2024-10-22 15:43 UTC, Astro-Kirsty commented
Ahh I see the issue! 
This is not really a deprecation as it is a dictionary.

I would suggest to make it a little less complicated and stay with the 'log.warning' idea (based off your class idea):

```
class ObservatoryDict(dict):
    def __missing__(self, key):
        if key == "cta_north":
            log.warning("The key 'cta_north' is incorrect. Automatically changing the location to 'ctao_north'.")
            return self["ctao_north"]
        else:
            raise KeyError(f"'{key}' not found in observatory locations.")

observatory_locations = ObservatoryDict()
"""Gamma-ray observatory locations (dict).....
"""
```

2024-10-22 15:46 UTC, bkhelifi commented
Indeed, this is a depreciation of a default value inside a dictionnary. This issue has happened couple of time and we had the only solution to send a log.info or log.warning to inform that the dict entry has changed.
One might add a dict_entry_depreciation in the utils... because this will happen in the future again and again

2024-10-22 16:11 UTC, morcuended commented
Thanks for the feedback @Astro-Kirsty, @bkhelifi! I'll work it out following your suggestions.

2025-01-16 11:42 UTC, AtreyeeS commented
What is the status here @morcuended ? 
I think the modification of deprecation warning can be an independent PR.

2025-01-17 11:09 UTC, morcuended commented
I stopped working on it. I will resume it next week.

2025-04-16 11:10 UTC, bkhelifi reviewed
Thank you a lot... I have some comments to this PR.

2025-04-16 11:10 UTC, bkhelifi commented on gammapy/datasets/simulate.py
>              if telescope == "CTA":
For the initial release, the stored metadata is really CTA?
For the next release, it might be CTAO. So I propose to add an OR condition with telescope == "CTAO"

To @morcuended and Matthias , should we keep in mind that the CTAO data releases will use the following metadata : 
- TELESCOP: "CTAO"
- INSTRUME: "Southern Array" and "Northern Array"
Is it the anticipated standard values?

2025-04-16 11:10 UTC, bkhelifi commented on gammapy/utils/deprecation.py
> +    Raise a deprecation warning if provided key is deprecated.
```suggestion
    Raise a deprecation warning if the provided key is deprecated.
```

2025-04-16 12:12 UTC, Astro-Kirsty commented on gammapy/utils/observers.py
> +
Maybe we can add these in a separate PR?

2025-04-16 12:13 UTC, Astro-Kirsty commented on gammapy/utils/observers.py
> +        }
As above

2025-04-17 10:49 UTC, QRemy requested changes
Is this PR only to rename ctao_south and ctao_north in observatory locations or introduce a larger concept of Observatory class, the latter should be a separate PR with a better design.

2025-04-17 10:49 UTC, QRemy commented on gammapy/utils/deprecation.py
> +def deprecated_key(key, old_keys, new_keys, since):
In my opinion the is not needed the keys are not deprecated but the module variable `observation_locations` is.

2025-04-17 10:49 UTC, QRemy commented on gammapy/utils/observers.py
> -observatory_locations = {}
This should not be deleted but instead

simply introduce:
```
class DeprecatedDict(dict):
    old_keys_to_new_keys = {'cta_south': 'ctao_south', 'cta_north': 'ctao_north'}
    def __getitem__(self, key):
        if key in self.old_keys_to_new_keys:
            msg = 'Please use the new key: `{}` instead of `{}`'.format(self.old_keys_to_new_keys[key], key)
            warn(msg)
        return super().__getitem__(key)
    def __setitem__(self, key, value):
        if key in self.old_keys_to_new_keys:
            msg = 'Please use the new key: `{}` instead of `{}`'.format(self.old_keys_to_new_keys[key], key)
            warn(msg, GammapyDeprecationWarning)
        return super().__setitem__(key, value)
        
observatory_locations = DeprecatedDict()        
```        

and you need nothing else to achieve what is in the title of the PR.

2025-04-17 10:49 UTC, QRemy commented on gammapy/utils/observers.py
> +class Observatories:
`Observatories` should be a list of `Observatory`, each  `Observatory` being a class including location as a property among others.

2025-04-17 11:01 UTC, registerrier reviewed
Thanks @morcuended and @Astro-Kirsty . This is good.

In general, I would even propose to remove this from gammapy and rely instead on astropy-data, though `EarthLocation.from_site()` adding entries there:
https://github.com/astropy/astropy-data/blob/gh-pages/coordinates/sites.json

Is there a good reason for us to have the list in gammapy rather than more broadly available to the community in astropy? Opinions @QRemy @AtreyeeS @bkhelifi @adonath ?

2025-04-17 12:14 UTC, Astro-Kirsty commented on gammapy/utils/observers.py
> -observatory_locations = {}
Yes, but the idea was to introduce a deprecation class for dictionaries in general. 

The only reason why we introduced a class is such that it can be correctly deprecated, while still behaving like a dictionary, which is why there are so many functions added.

2025-04-17 12:18 UTC, QRemy commented
> In general, I would even propose to remove this from gammapy and rely instead on astropy-data, though `EarthLocation.from_site()` adding entries there: https://github.com/astropy/astropy-data/blob/gh-pages/coordinates/sites.json

I agree if we can remove it that's even better. I guess we can still have a deprecation using the `DeprecatedDict ` class I mentioned above adding a warning on init that recommend to use `EarthLocation.from_site()` instead.

2025-04-17 12:36 UTC, QRemy commented on gammapy/utils/observers.py
> -observatory_locations = {}
`old_keys_to_new_keys` can be moved to init so this `DeprecatedDict` would be a general deprecation class for dictionaries

```
class DeprecatedDict(dict):
    old_keys_to_new_keys = {}
    def __init__(self, data, old_keys_to_new_keys):
        if old_keys_to_new_keys:
            self.old_keys_to_new_keys=old_keys_to_new_keys
        return super().__init__(data)
    
    def __getitem__(self, key):
        if key in self.old_keys_to_new_keys:
            msg = 'Please use the new key: `{}` instead of `{}`'.format(self.old_keys_to_new_keys[key], key)
            warn(msg)
        return super().__getitem__(key)
    def __setitem__(self, key, value):
        if key in self.old_keys_to_new_keys:
            msg = 'Please use the new key: `{}` instead of `{}`'.format(self.old_keys_to_new_keys[key], key)
            warn(msg, GammapyDeprecationWarning)
        return super().__setitem__(key, value)
 
observatory_locations = DeprecatedDict(observatory_locations, {'cta_south': 'ctao_south', 'cta_north': 'ctao_north'})   

```
observatory_locations = DeprecatedDict()

2025-04-17 14:08 UTC, Astro-Kirsty commented on gammapy/utils/observers.py
> -observatory_locations = {}
Okay, but dont we still need the other items to ensure it acts exactly like a dictionary?

2025-04-17 15:17 UTC, QRemy commented on gammapy/utils/observers.py
> -observatory_locations = {}
no it inherits from dict class

2025-04-17 15:30 UTC, QRemy commented on gammapy/utils/observers.py
> -observatory_locations = {}
only the new key will defined in `observatory_locations` but the old key will also work and emit a warning.

2025-04-17 15:44 UTC, Astro-Kirsty commented on gammapy/utils/observers.py
> -observatory_locations = {}
Yes, apologies, my script was outdated

2025-04-17 17:37 UTC, QRemy reviewed
Thanks @Astro-Kirsty for the update, just few remaining comments:

2025-04-17 17:37 UTC, QRemy commented on gammapy/utils/deprecation.py
> +def deprecated_key(key, old_keys, new_keys, since):
this is no longer needed right ?

2025-04-17 17:37 UTC, QRemy commented on gammapy/utils/deprecation.py
> +class DeprecatedDict(dict):
this should probably go in a separate PR first with its own unit tests.

2025-04-18 07:32 UTC, registerrier commented
On second thought, I fear that this is getting way too complex for such a small problem.

What this shows is that the whole idea of the observatory dictionary is not a good design as it does not allow several names for a given observatory nor for deprecation. (and in general all global variables suffer from this).
 
My proposal for a simple short term solution is to duplicate ctao entries with `"ctao_north"` and  `"ctao_south"` as keys and only show the latter in the docs, if the name change is considered important enough. 
Then we have to decide on what functionalities and design for the observatory locations registry in gammapy.

2025-04-30 13:56 UTC, QRemy commented
> My proposal for a simple short term solution is to duplicate ctao entries with `"ctao_north"` and `"ctao_south"` as keys and only show the latter in the docs, if the name change is considered important enough. Then we have to decide on what functionalities and design for the observatory locations registry in gammapy.

I agree just pushed a commit to remove the deprecation system and just duplicated the entries, will merge as soon as the CI pass.

2025-04-30 18:46 UTC, merged