Improve DL4 irfs support in gammapy.makers
gammapy/gammapy pull request #5632
Opened 2024-12-06 10:11 UTC by QRemy

Improve DL4 IRFs support in gammapy.makers implementing these features:
- Support for background maps given as a rate not only counts.
- Support for aeff and background given per transit.
- Add n_transits property in gti.
This is required to use SWGO IRFs.

2024-12-13 18:44 UTC, QRemy commented on gammapy/data/gti.py
> +            return self.gti.time_sum.to("transit")
```suggestion
            return self.time_sum.to("transit")
```

2024-12-13 19:04 UTC, adonath commented
Thanks @QRemy, it would be great if @LauraOlivera could review!

2024-12-19 17:01 UTC, LauraOlivera submitted a review, later dismissed
It looks good to me! I left an inline comment but I think the current implementation is fine as is. We should then build on this by implementing a function that derives `n_transits` as a function of R.A. (which is more time consuming...)

Thanks a lot @QRemy

2024-12-20 08:27 UTC, registerrier reviewed
Thanks @Qremy and @LauraOlivera .

Having `n_transit` as a property on `GTI` is confusing, as it applies only to specific situations and is rather a time unit conversion. I would rather have a new unit defined and perform a time conversion (`GTI.time_sum.to("transit")`). But if the unit is the same as `day` maybe it is even not really useful no?

Also, the choice of having the exposure per transit stored as a simple `Map` does not really guarantee that you can properly handle it, no? 
The unit is equivalent to a surface which does not really tell you that this is per transit. Isn't it better to have a dedicated IRF? Storing effective are as a function of zenith angle is not an option here?

2024-12-20 08:27 UTC, registerrier commented on gammapy/makers/map.py
> +            elif aeff.unit.is_equivalent(u.Unit("m2 s sday-1")):
This does not guarantee that the aeff map will be properly normalized as exposure per transit as any map with a area unit will comply.
Maybe a meta information could be used instead? Or a dedicated IRF object

2025-01-29 09:36 UTC, QRemy commented on gammapy/makers/map.py
> +            elif aeff.unit.is_equivalent(u.Unit("m2 s sday-1")):
now it also checks that "transit" is in the unit

2025-01-31 11:17 UTC, QRemy commented
Test added now it requires https://github.com/gammapy/gammapy-data/pull/66.

2025-02-17 09:22 UTC, bkhelifi requested changes
Thank you Quentin. I put some comments to be discussed and some improvement proposal.

2025-02-17 09:22 UTC, bkhelifi commented on gammapy/data/observations.py
> +    def gti(self, value):
At the GADF DL3, the data should contain the GTI (see https://gamma-astro-data-formats.readthedocs.io/en/v0.3/general/hduclass.html). However, a science analysis tool can change the GTI for its internal purpose (see 
https://gamma-astro-data-formats.readthedocs.io/en/v0.3/events/gti.html).
So, having a setter makes sense.
However:
1. one should be sure very cautious to not araise existing GTI (for provenance)
2. one should create our own Gammapy time interval (or a `UserTimeInterval`) in order to not mix the concepts. This becomes more and more important.

I propose here to add in the code a test forbidding to erase existing DL3 GTI

2025-02-17 09:22 UTC, bkhelifi commented on gammapy/maps/core.py
> +u.add_enabled_units([u.def_unit("transit", u.sday)])
We are creating here an unit, that is not listed as an international unit. Is it wise? Is it really the proper way to do it?
A full documentation is needed into Gammapy in case we accept to create a standard

2025-02-17 12:56 UTC, QRemy commented on gammapy/data/gti.py
> +            return self.time_sum.to("transit")
> This is the only part that makes me slightly nervous, because the definition of a transit as a unit is not very well defined for fractional transits (generally non-integer n_transits < 10 I would say).

This is for transient right ? In that case I think the irf should not be given per transit but integrated over the specific time range they have been derived for.

2025-02-17 13:02 UTC, QRemy commented on gammapy/data/gti.py
> +            return self.time_sum.to("transit")
> This equivalence of total time in GTI = number of transits observed is only true if the exposure is flat in right ascension.
> For the current HAWC and SWGO analyses, this is at the moment not a concern because in HAWC we select our data so that n_transits is constant in R.A., and since SWGO doesn't exist, we assume that is also the case.

I guess we can check that there is only one RA bin in the irfs and rise a `NotImplementedError` if that's not the case

2025-02-17 13:07 UTC, QRemy commented on gammapy/maps/core.py
> +u.add_enabled_units([u.def_unit("transit", u.sday)])
The problem is that the irfs for simulations are typically defined per transit while for real data they integrated over the full livetime.
@LauraOlivera prefers to not use sday explicitly in the unit, I'll let her explain why.

2025-02-17 13:16 UTC, LauraOlivera commented on gammapy/maps/core.py
> +u.add_enabled_units([u.def_unit("transit", u.sday)])
The DL4 IRFs are integrated over one transit (for the simplest analysis use case). A transit is defined through a zenith threshold (which should be part of the metadata), and it corresponds to the path a source does over the observatory from when it rises above the zenith threshold to when it goes below it.

In the span of 1 sidereal day, all visible sources will complete their transits. But the amount of *time* that one transit corresponds to depends on what is the declination of the source. Some sources will spend a minute above the zenith threshold, some others will spend the maximum amount (which is ~6h for a 45º zenith cut, so much less than 23.9h).

So it would be incorrect to say that the exposure is 1 sday, because this corresponds to 23.9h ,but the real exposure depends on the declination. So the correct unit is one transit.

If one has >>10 transits in the data and relatively flat exposure (which is common for WCDs), it is safe to assume that N sday in the exposure correspond to N transits, like Quentin implemented. This is not true for short exposures of course (which is what I mentioned above)

2025-02-17 16:18 UTC, bkhelifi commented on gammapy/maps/core.py
> +u.add_enabled_units([u.def_unit("transit", u.sday)])
Personally, I have no issue to "define" what is a transit. Fermi has the notion of "orbit", is not it?
If we use it, one should define it properly into the documentation, e.g.:
- the data reduction user guide
- the glossary

2025-02-19 10:51 UTC, QRemy commented on gammapy/data/observations.py
> +    def gti(self, value):
Maybe we can raise an error only if a GTI and the events exits because for simulation we can use flexibility in redefining the GTI.

2025-02-19 10:56 UTC, bkhelifi commented on gammapy/data/observations.py
> +    def gti(self, value):
Indeed, when both exist, a error could be raised. This guaranties to not detroy DL3 data

2025-03-21 14:16 UTC, QRemy commented on gammapy/maps/core.py
> +u.add_enabled_units([u.def_unit("transit", u.sday)])
glossary :  done #5735
the data reduction user guide : it's very light so I don't see how it would fit in there, I will suggest to have that in the HAWC or SWGO notebook instead in a separate PR.

2025-03-21 14:52 UTC, QRemy commented on gammapy/data/observations.py
> +    def gti(self, value):
done

2025-03-21 15:25 UTC, LauraOlivera submitted a review, later dismissed
Thanks, @QRemy, looks good to me besides something very minor

2025-03-21 15:25 UTC, LauraOlivera commented on gammapy/makers/map.py
> +                        factor = observation.gti.time_sum.to("transit")
maybe put the TODO here too so that it doesn't slip past?

2025-03-21 16:20 UTC, QRemy commented on gammapy/data/gti.py
> +            return self.time_sum.to("transit")
added TODO

2025-03-21 16:20 UTC, QRemy commented on gammapy/makers/map.py
> +                        factor = observation.gti.time_sum.to("transit")
added TODO

2025-03-21 16:23 UTC, QRemy commented
All commets are implemented, merging now.

2025-03-21 16:23 UTC, merged